<?php

return [

    'verify_your_account' => 'Please verify your account to log in to your account.',
    'user_not_exists' => 'هذا المستخدم غير موجود',
    'user_exists' => 'هذاالمستخدم موجود من قبل',
    'successfully_logged_in' => 'Successfully logged in',
    'successfully_logged_out' => 'تم تسجيل الخروج بنجاح',
    'cart_is_empty' => 'Your cart is empty',
    'not_found_this_market' => 'Not Found This Market',
    'this_product_is_not_currently_available' => 'هذا المنتج غير متاح الان',
    'qty_should_be_between_1_' => 'Qty should be between 1 : ',
    'you_must_specify_one_market' => 'You must specify one market',
    'you_have_products_from_another_market' => 'You have products from another market',
    'You_Must_Select_One_Option_for_Each_Available_Attribute' => 'You Must Select One Option for Each Available Attribute',
    'Product_has_been_added_to_your_cart' => 'Product has been added to your cart',
    'Not_Found_This_Item_on_Your_Cart' => 'Not Found This Item on Your Cart',
    'This_product_is_not_currently_available' => 'هذا المنتج غير متاح الان',
    'Product_quantity_has_been_updated_in_your_cart' => 'Product quantity has been updated in your cart',
    'The_required_quantity_should_not_exceed' => 'The required quantity should not exceed ',
    'Your_Cart_has_been_Deleted' => 'Your Cart has been Deleted',
    'This_cart_item_not_exists' => 'This cart item not exists',
    'The_cart_item_has_been_deleted' => 'The cart item has been deleted',
    'message_successfully_sent' => 'message successfully sent',
    'Something_went_wrong_please_try_again_later' => 'Something went wrong, please try again later',
    'Product_Nom' => 'Product Nom: ',
    'Not_Availabe_for_Now' => 'غير متاح',
    'The_total_price_less_than_market_minimum_purchase' => 'اجمالي الطلب اقل من الحد الادنى للمتجر',
    'Not_Found_This_Copoun' => 'الكود المستخدم غير صحيح',
    'Invalid_Copoun' => 'الكود المستخدم غير صحيح',
    'The_Order_has_been_Created' => 'تم عمل الطلب بنجاح',
    'Not_found_this_order' => 'Not found this order',
    'Order_already_canceled' => 'تم الغاء الطلب',
    'You_can_not_cancel_this_order_until_it_has_been_accepted' => 'You can not cancel this order ,until it has been accepted',
    'The_order_has_been_canceled' => 'تم الغاء الطلب',
    'The_order_process_has_not_yet_been_completed' => 'The order process has not yet been completed',
    'You_have_already_evaluated_this_order' => 'You have already evaluated this order',
    'The_order_has_been_evaluated' => 'The order has been evaluated',
    'This_product_is_not_belongs_to_this_order' => 'This product is not belongs to this order',
    'You_have_already_evaluated_this_product_of_this_order' => 'You have already evaluated this product of this order',
    'The_order_product_has_been_evaluated' => 'The order\'s product has been evaluated',
    'The_Order_has_not_yet_been_prepared' => 'The Order has not yet been prepared',
    'Still_the_delivery_has_not_received_your_order_yet' => 'Still the delivery has not received your order yet',
    'The_Order_has_not_yet_been_processed' => 'The Order has not yet been processed',
    'Driver_coordinates_has_been_updated' => 'تم تحديث الموقع بنجاح',
    'not_found_this_copoun' => 'الكود المستخدم غير صحيح',
    'expired_copoun' => 'الكود المستخدم منتهي',
    'Not_found_this_product' => 'Not found this product',
    'User_Profile_has_been_updated' => 'تم تحديث البيانات بنجاح',
    'Account_deleted_successfully' => 'تم حذف الحساب بنجاح',
    'Location_added' => 'تم اضافة العنوان بنجاح',
    'Not_found_this_location' => 'هذا العنوان غير موجود',
    'Location_Updated' => 'تم تعديل العنوان بنجاح',
    'Location_Deleted' => 'تم حذف العنوان بنجاح',
    'FCM_Token_mobile_id_have_been_updated' => 'fcm_token & mobile_id have been updated',
    'Driver_not_exists' => 'Driver not exists',
    'Token_dosnt_generated' => 'Token dosn\'t generated',
    'Wait_the_admin_has_not_accepted_this_order_yet' => 'Wait, the admin has not accepted this order yet',
    'This_order_belongs_to_another_driver' => 'تم قبول الطلب من مندوب آخر',
    'This_Order_has_been_added_to_your_current_orders' => 'This Order has been added to your current orders',
    'This_order_already_added_to_rejected_list' => 'This order already added to rejected list',
    'The_order_was_excluded_from_the_orders_list' => 'The order was excluded from the orders list',
    'Order_Status_not_Prepared' => 'Order Status not Prepared',
    'You_have_already_changed_this_status' => 'You have already changed this status',
    'You_have_been_changed_the_order_status_to_on_the_way_to_customer' => 'تم تغيير حالة الطلب الى في الطريق',
    'Order_Status_Error_not_Prepared_or_You_have_already_changed_this_status' => 'Order Status Error , not Prepared or You have already changed this status',
    'You_have_been_changed_the_order_status_to_Delivered' => 'تم تغيير حالة الطلب الى تم التوصيل',
    'Driver_Profile_has_been_updated' => 'تم تحديث البيانات بنجاح',
    'You_has_been_Marked_Your_Chats_as_Seen' => 'You has been Marked Your Chats as Seen',
    'Your_Notifications_Orders_that_Accepted_by_the_Admin' => 'Your Notifications & Orders that Accepted by the Admin',
    'Password_successfully' => 'تم تغيير كلمة المرور بنجاح',
    'Not_Password_successfully' => 'لم يتم تغيير كلمة المرور حاول مره ثانية',
    'Old_Password_Doesnt_match' =>'كلمة المرور القديمة غير متطابقة!',
    'Password_changed_successfully' => 'تم تغيير كلمة المرور بنجاح',
    'complaint_successfully' => 'تم تسجيل الشكوى بنجاح',
    'Not_complaint_successfully' => 'عفوا حاول مره اخر لتسجيل الشكوى',
    'contact_successfully' => 'تم ارسال الرسالة بنجاح',
    'Not_contact_successfully' => 'عفوا حاول مره ثانية',
    'updateBalance_successfully' => 'تم تحديث الرصيد بنجاح',

    'add_review_successfully' => 'تم اضافة التقييم بنجاح',

    'Been_Completed_Order' => 'شكرا لك على تنفيذ الخدمة',
    'successfully' => 'تم التحديث بنجاح',
    'the_code_is_invalid' => 'رقم الكارت غلط',
    'successfully_added' => 'تم الاضافة بنجاح',


    // '' => '',



];
