<?php

return [
    'app_name'      => 'Moeein App',
    'cats'          => 'Categories',
    'who_us'        => 'Who Us',
    'contact_us'    => 'Contact Us',
    'logout' => 'Logout',
    'app_screens'   => 'App Screens',
    'intro'         => 'Your Real Estate Is Now In Your Hands',
    'intro_desc'    => 'Buy and sell easily and conveniently all you need from real estate and cars',
    'google_play'   => 'Google Play',
    'app_store'     => 'App Store',
    'app_features'  => 'App Features',
    'easy_feature'  => 'Ease Of Use',
    'easy_feature_desc' => 'Browse the application easily and conveniently now',
    'many_ads_feature' => 'Many Ads',
    'many_ads_feature_desc' => 'Moeein allows you to choose from many advertisements displayed',
    'subscribe_feature' => 'Easily Select Subscription',
    'subscribe_feature_desc' => 'The application provides you with many subscriptions to choose what suits you',
    'near_feature'  => 'The Nearest Real Estate Or Cars To Your Location',
    'near_feature_desc' => 'The application determines the nearest real estate to your location',
    'main_cats'     => 'Main Categories',
    'main_cats_desc' => 'Choose what you need for sale or rent',
    'download_app'  => 'Download App The Application Now',
    'everything_you_need' => 'You can now get everything you need with Khiarak',
    'favorite' => 'Favorite',
    'wish' => 'Wishlist',
    'register' => 'Register',
    'login' => 'Login',
    'diff_levels' => 'Multiple Categories',
    'auth_dealers' => 'Authorized Dealers',
    'who_us_para1' => 'In order to become a member of the application, you must first fill out the registration form, then agree and undertake to abide by the terms of use, and upon approval of the registration, you agree to our terms and conditions',
    'who_us_para2' => 'The application reserves the right to modify these terms of use at any time and without prior notice, and that you agree that each visit you make to the application will be subject to the applicable terms of use at this time, and that your use of the application at any time confirms that you have read and agreed to these provisions and Conditions',
    'choose_cat' => 'Choose the category you want',
    'newest_ads' => 'Latest Posted Ads',


];
