<?php

return [


    'name_fr'           =>'Norway Name',
    'desc_fr'           =>'Description Name',
    'price_additional_interface' => 'Price Additional Interface',

    'app_name'          => 'khiark',
    //Login Page
    'access'            => 'Access to our dashboard',
    'login'             => 'Login',
    'username'          => 'User Name',
    'password'          => 'Password',
    'rep_password'      => 'confirm Password',
    'forg_pass'         => 'Forgot password?',
    'logout'            => 'Logout',
    'error_credentials' => 'Try With Correct Email and Password!!',
    'succes_login'      => 'You are logged in successfully',
    'registSuccess'     => 'Registerd successfully',
    'false_info'        => 'False information please try again',
    'new_pass'          => 'Changed password successfully',
    'usernotexist'      => 'User not exist',
    'rateSuccess'       => 'Rate successfully',
    'userlocationexist' => 'Provider location exist',
    'reqLat'            => 'Latitude is required',
    'reqLong'           => 'longitude is required',
    'locationSuccess'   => 'Location added successfully',
    'latitude'           => 'your location details is requird',
    'longitude'         => 'your location details is required',
    'map'         => 'Map',
    'send_noty'         => 'Send Notification',
    'sended_successfully'         => 'Sended Successfully',

    'brofits'         => 'Profits',
    'trips_count'         => 'Trips Count',
    'total_brofits'         => 'Total Profits',
    'today_brofits'         => 'Today Profits',
    'tatal_tax'         => 'Tatal Tax',
    'statuss'                =>'Status',
    'main_reports'                =>'Trips Reports',
    'coose_statuss'                =>'Choose Status',
    'export_to_excel'                =>'Export to Excel',
    'export_to_pdf'                =>'Export to PDF',
    'commission_due'                =>'Commission Due',

    //Common
    'incorrect_info' => 'Incorrect Info',
    'no_data_found'  => 'No Data Found',
    'no_records'     => 'No Records',
    'menu'           => 'Menu',
    'search'         => 'Search',
    'operations'     => 'Operations',
    'edit'           => 'Edit',
    'delete'         => 'Delete',
    'add'            => 'Create',
    'show'           => 'Show',
    'permission'     => 'Permission',
    'confirm_delete' => 'Confirm Delete',
    'yes'            => 'Yes',
    'no'             => 'No',
    'submit'         => 'Submit',
    'name'           => 'Name',
    'verify_code'    => 'Verification Code',
    'your_verify_code'=> 'Your verification Code: ',
    'unverified_account'=> "Your account isn't verified",
    'wrong_code'      => 'Wrong Code',
    'code_sent'       => 'Code successfully sent',
    'your_verify_code' => 'Your Verification Code: ',
    'account_not_active'=>'Your account has not been activated',

    'unique_username'    => 'Username exist',
    'reqEmail'           => 'Email is required',
    'unique_email'       => 'Email exist',
    'req_password'       => 'Password is required',
    'password_confirmed' => 'Password is incorrect',
    'not_enough_balance' => 'You do not have enough balance',

    'reqCountry'   => 'Country is required',
    'reqAddress'   => 'Address is required',
    'reqImageID'   => 'Image ID is required',
    'reqCats'      => 'Choose category is required',
    'reqSubs'      => 'Choose Subscription type is required',

    'reqPhone'      => 'Phone number is required',
    'uniquePhone'   => 'Phone number is already exist',

    'wrang_phone'   => 'Wrong Phone',
    'sent_phone'    => 'Code sent successfuly',

    'create' => 'Add',
    'update' => 'Update',
    'read'   => 'Read',
    'users'  => 'Users',


    'old_password'                 => 'Old Password',
    'new_password'                 => 'New Password',
    'update_profile'               => 'Update Profile',
    'change_password'              => 'Change Password',
    'changed_password_successfully'=> 'Changed Password Successfully',
    'passwords_not_valid'          =>'Passwords Not Valid',

    'added_successfully'   => 'Added Successfully',
    'updated_successfully' => 'Updated Successfully',
    'deleted_successfully' => 'Deleted Successfully',
    'canceled_successfully' => 'has canceled the trip',

    //NavBar
    'main'  => 'Dashboard',
    'user'  => 'Users',

    //Admins Page
    'username'     => 'Username',
    'email'        => 'Email',
    'image'        => 'Image',
    'add_new_user' => 'Add New User',
    'edit_user'    => 'Edit User',
    'first_name'   => 'First Name',
    'last_name'    => 'Last Name',

    'req_first_name'     => 'First name is required',
    'req_last_name'      => 'Last name is required',
    'req_username'       => 'Username is required',
    'unique_username'    => 'Username exist',
    'unique_email'       => 'Email exist',
    'req_password'       => 'Password is required',
    'password_confirmed' => 'Password is incorrect',

    // Profile
    'profile'               => 'My Profile',
    'editProfile'           => 'Edit Profile',
    'setting'               => 'Setting',
    'changPass'             => 'Change Password',
    'oldPass'               => 'Old Password',
    'newPass'               => 'New Password',
    'password_confirmation' => 'New Password Confirmation',
    'balance'               => 'Balance',

    // Setting
    'technical-support'  => 'Technical Support',
    'instegram'          => 'Instegram',
    'facebook'           => 'Facebook',
    'paying'             => 'Paying',
    'terms'              => 'Terms and Conditions',
    'term_ar'            => 'Term in arabic',
    'term_en'            => 'Term in english',
    'term_fr'            => 'Term in Norway',
    'general'            => 'General',
    'min_order'          => 'Minimum order value',
    'confirm_renew'      => 'Are you sure?',
    'confirm_complete'   => 'Are you sure to complete?',
    'payment_api_token'  => 'Payment API Key',
    'max_distance'       => 'Max distance from driver',
    'help_questions'     => 'Help Questions',
    'question'           => 'Question',
    'answer'             => 'Answer',
    'question_ar'        => 'Arabic Question',
    'question_en'        => 'English Question',
    'question_fr'        => 'Norway Question',
    'answer_ar'          => 'Arabic Answer',
    'answer_en'          => 'English Answer',
    'answer_fr'          => 'Norway Answer',
    'users_reports'      => 'Users Reports',
    'message'            => 'Message',
    'trip'               => 'Trip',
    'app_tirp_percent'   => 'App Tirp Percent',
    'referral_code_price'=> 'Referral code price',
    'referral_code_trips'=> 'Apply referral code after how many trips?',


    // Categories

    'cats'         => 'Categories',
    'cat_name'     => 'Category Name',
    'subcats'      => 'Subcategories',
    'addNewCat'    => 'Add New Category',
    'catAr'        => 'Category in arabic',
    'catEn'        => 'Category in english',
    'chooseCat'    => 'Choose category (Main category)',
    'reqCatAr'     => 'Category name in arabic is required',
    'uniqueCatAr'  => 'Category name is arabic is exist',
    'reqCatEn'     => 'Category name in english is required',
    'uniqueCatEn'  => 'Category name is english is exist',
    'reqImage'     => 'Image is required',
    'attrType'     =>'Attribute Type',
    'textAttr'     =>'Text Attribute',
    'numericAttr'  => 'Numeric Attribute',
    'multichoiceAttr'=>'Multichoice Attribute',
    'type_name'     => 'Type Name',
    'type_name_ar'  => 'Arabic Type Name',
    'type_name_en'  => 'English Type Name',
    'type_name_fr'  => 'Norway Type Name',
    'details_name'  => 'Details Name',
    'details_name_ar'  => 'Arabic Details Name',
    'details_name_en'  => 'English Details Name',
    'details_name_fr'  => 'Norway Details Name',
    'subtitle'      =>'Subtitle',
    'subtitle_ar'   =>'Arabic Subtitle',
    'subtitle_en'   =>'English Subtitle',
    'subtitle_fr'   =>'Norway Subtitle',
    'price_for_kilo'=>'Price For Kilo',

    //brands
    'brands'        =>'Brands',
    'cars'          =>'Cars',
    'colors'        =>'Colors',
    'manufacturing_years'=>'Manufacturing Years',
    'year'          =>'Year',



    //restaurants
    'restaurants'           =>'Restaurants',
    'restaurant_name'       =>'Restaurant Name',
    'orders'                =>'Orders',
    'items'                 =>'Items',

    //driver
    'drivers'               =>'Drivers',
    'driver_name'           =>'Driver Name',
    'registration_number'   =>'ID Number/Location',
    'deactivate'            =>'Deactivate The Account',
    'activate'              =>'Activate The Account',
    'car_details'           =>'Car Details',
    'brand'                 =>'Brand',
    'color'                 =>'Color',
    'car'                   =>'Car',
    'manufacturing_year'    =>'Manufacturing year',
    'car_number'            =>'car_number',
    'car_front_image'       =>'Car front image',
    'car_back_image'        =>'Car Back Image',
    'car_form_image'        =>'Car form image',
    'car_license_image'     =>'Car license image',
    'driving_license_image' =>'Driving license image',

    //bundles
    'desc_ar'               =>'Arabic Description',
    'desc_en'               =>'English Description',
    'desc_fr'               =>'Norway Description',
    'bundles'               =>'Bundles',
    'bundle'                =>'Bundle',
    'subscription_status'   =>'Subscription Status',
    'active'                =>'Active',
    'inactive'              =>'Inactive',
    'renew'                 =>'Renew',
    'paid_price'            =>'Paid Price',
    'delivered_price'       =>'Delivered Price',

    //trips
    'trips'                 =>'Trips',
    'customer_phone'        =>'Customer Phone',
    'trip_status'           =>'Trip Status',
    'src_address'           =>'Source Address',
    'src_lat'               =>'Source Latitude',
    'src_lng'               =>'Source Longitude',
    'dest_address'          =>'Destination Address',
    'dest_lat'              =>'Destination Latitude',
    'dest_lng'              =>'Destination Longitude',
    'tax_value'             =>'Tax Value',
    'trip_details'          =>'Trip Details',
    'no_near_cars'          =>'There are no cars near you, please try again later',

    //bank_accounts
    'bank_accounts'         =>'Bank Accounts',
    'bank_name_ar'          =>'Arabic Bank Name',
    'bank_name_en'          =>'English Bank Name',
    'bank_name_fr'          =>'Norway Bank Name',
    'account_owner_name'    =>'Account Owner Name',
    'account_number'        =>'Account Number',
    'iban'                  =>'IBAN',
    'deposits'              =>'Deposits',
    'receipt'               =>'Receipt',
    'completed'             =>'Completed',
    'complete'              =>'Complete',

    'android_app_link'      =>'Android App Link',

    //coupons
    'coupons'       => 'Promotions',
    'coupon_code'   => 'Coupon Code',
    'discount_percent'=> 'Discount Percent',
    'count_of_use'  => 'Count Of Use',
    'times_for_user'=>'Times count for user',
    'false_coupon'  => 'False coupon code!',
    'coupon_type'       =>'Coupon Type',
    'percent'           =>'Percent',
    'discount_max_value'=>'Discount Max Value',
    'discount_value'    =>'Discount Value',
    'coupon_value'  =>'Value',
    'count_of_trips'    =>'Count of Trips',

    //feedback
    'feedback'      => 'Users Feedback',
    'content'       => 'Message Content',
    'user_name'     => 'User Name',



    // Country

    'country'            => 'Countries',
    'state'              => 'Country',
    'countryAr'          => 'Country in arabic',
    'countryEn'          => 'Country in english',
    'reqStatNameAr'      => 'Country in arabic is required',
    'reqStatNameEn'      => 'Country in english is required',
    'uniqueStatNameEn'   => 'Country in arabic is exist',
    'uniqueStatNameAr'   => 'Country in english is exist',
    'govern'             => 'Cities',
    'governAr'           => 'City in arabic',
    'governEn'           => 'City in english',
    'reqGovernNameAr'    => 'City in arabic is required',
    'reqGovernNameEn'    => 'City in arabic is required',
    'uniqueGovernNameEn' => 'City in english is exist',
    'uniqueGovernNameAr' => 'City in english is exist',

    'districts'          =>'Districts',
    'district_ar'        =>'District In Arabic',
    'district_en'        =>'District In English',
    'district_en'        =>'District In Norway',

    'countries'          =>'Countries',
    'country_name'       =>'Country Name',
    'choose_country'     =>'Choose country',
    'select_country'     =>'Choose country',
    'currencies'         =>'Currencies',
    'choose_currency'    =>'Choose currency',

    // Providers
    'provider'   => 'Providers',
    'job'        => 'Job',
    'phone'      => 'Phone',
    'address'    => 'Address',
    'idImage'    => 'ID Image',
    'info'       => 'Descreptions',


    // customers
    'customers'  => 'Customers',
    'location'   => 'Location',
    'lat'        => 'latitude',
    'long'       => 'Longitude',

    'substra'    => 'subscription',
    'substras'   => 'subscriptions',
    'price'      => 'Price',
    'subDesc'    => 'Subscription Detials',
    'substraAr'  => 'Subscription in arabic',
    'substraEn'  => 'Subscription in english',
    'subsDescAr' => 'Description in arabic',
    'subsDescEn' => 'Description in english',
    'reqInputAr' => 'Input in arabic is required',
    'reqInputEn' => 'Input in english is required',
    'reqDescAr'  => 'Description in arabic is required',
    'reqDescEn'  => 'Description in english is required',
    'uniInputAr' => 'Input in arabic is exist before',
    'uniInputEn' => 'Input in english is exist before',
    'rate'       => 'Rate',
    'slider'     => 'Slider',
    'sliders'    => 'Slider',
    'contactUs'  => 'Contact us',
    'aboutAs'    => 'About us',
    'about'      => 'About us',
    'reqPrice'   => 'Price is required',
    'website'    => 'Website',
    'wallet'     => 'Wallet Balance',
    'add_balance'=> 'Add Balance',


     // Api
     'reqCustomer'  => 'Customer is required',
     'reqProvider'  => 'Provider is required',
     'reqRate'      => 'Rate is required',
     'addedCart'    => 'Product has been added to Cart',


    // Subscriptions
    'subscriptions'         =>'Subscriptions',
    'ads_number'            =>'Ads Number',
    'subscription_name_ar'  =>'Subscription Name In Arabic',
    'subscription_name_en'  =>'Subscription Name In English',
    'subscription_name_fr'  =>'Subscription Name In Norway',
    'ad_fees'               =>'Single Advertisement Fees',
    'ad_expiration'         =>'Advertisement Expiration In Days',
    'advertisement_fees_expiration'=>'AD Fees and Expiration',

    //advertisements
    'advertisement_types'   =>'Advertisements Types',
    'advertisements'        =>'Advertisements',
    'nameAr'                =>'Arabic Name',
    'nameEn'                =>'English Name',
    'start_date'            =>'Start Date',
    'end_date'              =>'End Date',
    'type'                  =>'Advertisement Type',
    'status'                =>'Advertisement Status',
    'advertisement_details' =>'Advertisement Details',
    'current'               =>'Current',
    'finished'              =>'Finished',

    //verify to deelte
    'yes'  =>'Yes',
    'no'   =>'No',
    'confirm_delete' =>'Are you sure to delete',

    //dashboard index
    'show'      => 'Show',

    'subscription'=>'Subscription',
    'admin'     =>'Admins',

    //notifications
    'notifications'     =>'Notifications',
    'title'             =>'Title',
    'title_ar'          =>'Arabic Title',
    'title_en'          =>'English Title',
    'title_fr'          =>'Norway Title',
    'body'              =>'Body',
    'body_ar'           =>'Arabic Body',
    'body_en'           =>'English Body',
    'body_fr'           =>'Norway Body',
    'all'               =>'Send to All',
    'send'              =>'Send',
    'add_notify'        =>'Add Notification',
    'desire_matching_title'=>'ًWishlist',
    'desire_matching_body' =>'An ad that matches your wishlist has been found',
    'chat_notify_title'    =>'Message from: ',
    'chat_notify_body'     =>'',
    'saveToDatabase'       =>'Show it in App notifications',
    'timed_nots'           =>'Timed Notifications',

    'bundle_subscription'   =>'You have successfully subscribed to the bundle',
    'balance_adding'        =>'A balance has been added to your wallet: ',
    'balance_transfering'   =>'A balance has been transferred to you in the amount of: ',
    'referral_code_not'     =>'Due to the referral code used at registration you win with: ',
    'you_have_new_trip_not' =>'You have a new trip',
    'you_have_new_order_not' =>'You have a new order',
    'trip_acceptance_not'   =>'The driver is on the way to you',
    'order_acceptance_not'   =>'The driver is on the way to you',
    'trip_starting_not'     =>'The driver strated the trip',
    'trip_finishing_not'    =>'The trip has been finished',

    //sliders
    'slider_image_fr'   =>'Norway Slider Image',
    'slider_image_en'   =>'English Slider Image',
    'slider_image_ar'   =>'Arabic Slider Image',
    'slider_link'       =>'Slider Link',
    'select_category'   =>'Select Category',
    'select_subcat'=>'Select Subcategory',
    'subcat_name'       =>'Subcategory name',

    //subscriptions
    'subscribe_status'  =>'Subscription Status',
    'subscribe_status_valid'  =>'Valid',
    'subscribe_status_expired'  =>'Expired',
    'subscribe_name'    =>'Subscription Name',
    'subscribe_start_date'=>'Start Date',
    'subscribe_end_date'=>'End Date',
    'provider_subs'     =>'Providers Subscriptions',

    //pharmacy, delivery
    'pharmacy'          =>'Pharmacies',
    'delivery'          =>'Delivery',
    'customer'          =>'Customers',

    //products
    'products'          =>'Products',
    'desc'              =>'Description',
    'productAr'         =>'Arabic Product Name',
    'productEn'         =>'English Product Name',
    'descAr'            =>'Description in Arabic',
    'descEn'            =>'Description in English',
    'addNewProduct'     =>'Add New Product',
    'product_name'      =>'Product Name',
    'select_product'    =>'Select Product',
    'wholesale_price'   =>'Wholesale Price',
    'retail_price'      =>'Retail Price',
    'min_wholesale'     =>'Minimum Wholesale',
    'select_units'      =>'Select Units',
    'units'             =>'Units',
    'increase_by'       =>'Increase By',
    'related_products'  =>'Related Products',
    'retail_discount'   =>'Retail Discount',
    'retail_discount_end_date' =>'Retail Discount End Date',
    'wholesale_discount'=>'Wholesale Discount',
    'wholesale_discount_end_date'=>'Wholesale Discount End Date',


    //attributes
    'attributes'        =>'Atrributes',
    'subattr'           =>'Subattributes',
    'attr_name'         =>'Attribute Name',
    'attrAr'            => 'Arabic Attribute Name',
    'attrEn'            => 'English Attribute Name',
    'subattrAr'         => 'Arabic Subattribute Name',
    'subattrEn'         => 'English Subattribute Name',
    'value'             =>'Value',
    'attrIcon'          => 'Attribute Icon',

    //orders
    'order'             =>'Orders',
    'customerName'      =>'Customer Name',
    'subscribe'         =>'Subscribe',
    'paymentWay'        =>'Payment Way',
    'deliveryCost'      =>'Delivery Cost',
    'taxValue'          =>'Tax Value',
    'totalPrice'        =>'Total Price',
    'productName'       =>'Product Name',
    'quantity'          =>'Quantity',
    'date'              =>'Date',
    'orderDetails'      =>'Order Details',
    'orderCart'         =>'Order Cart',
    'new_order'         =>'New Order',
    'preparing'         =>'The order is being prepared',
    'delivering'        =>'Order is being delivered',
    'delivered'         =>'Order has been delivered',
    'wholesale'         =>'Wholesale',
    'retail'            =>'Retail',
    'buying_mode'       =>'Buying Mode',
    'visa'              =>'Visa',
    'cash'              =>'Cash',
    'wallet'            =>'Wallet',
    'kilo'              =>'Kilo',
    'box'               =>'Box',
    'buying_type'       =>'Buying Unit',
    'status_changed'    =>'Order status successfully changed',
    'cancel'            =>'Cancel',
    'canceled_orders'   =>'Canceled Orders',
    'change_order_status'=>'Change Order Status',
    'canceler_admin'    =>'Canceler Admin',

    'order_title'       =>'Order Title',
    'order_details'     =>'Order Details',
    'special_orders'    =>'Special Orders',
    'order_status'      =>'Order Status',
    'price_delivered'   =>'Price Delivered',
    'preparing_started' =>'Preparing Started',
    'finishing_closed'  =>'Finishing Closed',

    //payment notices
    'payment_notice'    =>'Payment Notice',

    //delivery distance
    'delivery_distance' =>'Delivery Distance',
    'from'              =>'From',
    'to'                =>'To',
    'delivery_price'     =>'Delivery Cost',

    //delivery times
    'delivery_times'     =>'Delivery Times',
    'delivery_time'     =>'Delivery Time',
    'period'             =>'Period',
    'am'                 =>'AM',
    'pm'                 =>'PM',
    'delivery_dates'     =>'Delivery Dates',
    'delivery_date'      =>'Delivery Date',
    'expired_date'       =>'Expired Date',


    //address types
    'address_types'     =>'Address Types',
    'name_ar'           =>'Arabic name',
    'name_en'           =>'English Name',
    'name_fr'           =>'Norway Name',
    'icon'              =>'Icon',

    //free delivery
    'free_delivery'     =>'Free Delivery',
    'day'               =>'Day',
    'out_distance'      =>'Distance is out of range',

    //about us
    'about_ar'          =>'About us in Arabic',
    'about_en'          =>'About us in English',
    'about_fr'          =>'About us in Norway',

    //delivery cost and tax
    'delivery_tax'      =>'Delivery Cost and Tax',
    'one_month_cost'    =>'Delivey cost for one month subscription',
    'three_month_cost'  =>'Delivey cost for three months subscription',
    'tax'               =>'Percentage of Tax',

    'not_enough_wallet'=>"You don't have enough balance in your wallet",
    'req_payment_method'=>'Payment method is required',
    'req_delivery_time'=>'Delivery time is required',
    'req_delivery_date'=>'Delivery date is required',
    'andriod_app_link'=>'Andriod app link',
    'ios_app_link'=>'IOS app link',

    'req_phone' => 'phone is required',



    'journy_end'            => 'Journey ends',
    'trip_over'             => 'Trip is over',
    'trip_number'           => 'Trip number',
    'distance'              => 'Distance',
    'total_price'           => 'Total Price',

    'low_price'             => 'Low Price',
    'waiting_cost'          => 'Waiting Cost',


    'trip_scheduled'          => 'The trip has been scheduled',
    'order_scheduled'          => 'The order has been scheduled',

    'on_site_trip' => 'The driver has arrived your location',
    'on_site_order' => 'The driver has arrived your location',
    'on_way' => 'On Way',
    'order_finishing_not' => 'Order Finishing',

    'company_name' => 'Company Name',
    'tax_record' => 'Tax Record',

    'review_added' => 'Review Added',

    'reject_offer_successfully' => 'Reject Offer Successfully',
    'reject_offer' => 'Your bid has Offer rejected and you can create another Offer',
    'reject_trip_successfully' => 'Reject Trip Successfully',
    'collecting_the_fare' => 'Collecting The Fare Successfully',
    'reject_order_successfully' => 'Reject Order Successfully',

    'New_trip'       => 'New',
    'Underway_trip'  => 'In Progress',
    'completed_trip' => 'Completed',
    'scheduled_trip' => 'Scheduled',
    'cancel_trip'    => 'Cancelled',
    'The_balance_is_insufficient' => 'The Balance Is Insufficient',
    'accept_Offer' => 'Your bid has been accepted',
    'trip_offer_not' => 'A new price quote has been sent',
    'order_received'=> 'The driver received the shipment',
    'order_delivery_point'=> 'The driver delivers the shipment',
    'count_offers' => 'Count Offers',
    'New_order'       => 'New',
    'receiving_point' => 'The Driver Receiving Point',
    'order_details' => 'Order Details',

    'photo_one' => 'Photo One',
    'photo_two' => 'Photo Two',
    'photo_three' => 'Photo Three',
    'app_order_percent' => 'App Order Percent',
    'order_end_time' => 'Order End Time',
    'no_driver_id'=>' no driver id',

    'banner' => 'Banner',
    'link_banner' => 'Banner',
    'image_banner' => 'Image Banner',
    'delete_image_banner' => 'Delete Image Banner',
    
];
