<?php

return [

    'verify_your_account' => 'Please verify your account to log in to your account.',
    'user_not_exists' => 'User not exists',
    'user_exists' => 'User exists',
    'successfully_logged_in' => 'Successfully logged in',
    'successfully_logged_out' => 'Successfully logged out',
    'cart_is_empty' => 'Your cart is empty',
    'not_found_this_market' => 'Not Found This Market',
    'this_product_is_not_currently_available' => 'This product is not currently available',
    'qty_should_be_between_1_' => 'Qty should be between 1 : ',
    'you_must_specify_one_market' => 'You must specify one market',
    'you_have_products_from_another_market' => 'You have products from another market',
    'You_Must_Select_One_Option_for_Each_Available_Attribute' => 'You Must Select One Option for Each Available Attribute',
    'Product_has_been_added_to_your_cart' => 'Product has been added to your cart',
    'Not_Found_This_Item_on_Your_Cart' => 'Not Found This Item on Your Cart',
    'This_product_is_not_currently_available' => 'This product is not currently available',
    'Product_quantity_has_been_updated_in_your_cart' => 'Product quantity has been updated in your cart',
    'The_required_quantity_should_not_exceed' => 'The required quantity should not exceed ',
    'Your_Cart_has_been_Deleted' => 'Your Cart has been Deleted',
    'This_cart_item_not_exists' => 'This cart item not exists',
    'The_cart_item_has_been_deleted' => 'The cart item has been deleted',
    'message_successfully_sent' => 'message successfully sent',
    'Something_went_wrong_please_try_again_later' => 'Something went wrong, please try again later',
    'Product_Nom' => 'Product Nom: ',
    'Not_Availabe_for_Now' => ' ,Not Availabe for Now',
    'The_total_price_less_than_market_minimum_purchase' => 'The total price less than market minimum purchase',
    'Not_Found_This_Copoun' => 'Not Found This Copoun',
    'Invalid_Copoun' => 'Invalid Copoun',
    'The_Order_has_been_Created' => 'The Order has been Created',
    'Not_found_this_order' => 'Not found this order',
    'Order_already_canceled' => 'Order already canceled',
    'You_can_not_cancel_this_order_until_it_has_been_accepted' => 'You can not cancel this order ,until it has been accepted',
    'The_order_has_been_canceled' => 'The order has been canceled',
    'The_order_process_has_not_yet_been_completed' => 'The order process has not yet been completed',
    'You_have_already_evaluated_this_order' => 'You have already evaluated this order',
    'The_order_has_been_evaluated' => 'The order has been evaluated',
    'This_product_is_not_belongs_to_this_order' => 'This product is not belongs to this order',
    'You_have_already_evaluated_this_product_of_this_order' => 'You have already evaluated this product of this order',
    'The_order_product_has_been_evaluated' => 'The order\'s product has been evaluated',
    'The_Order_has_not_yet_been_prepared' => 'The Order has not yet been prepared',
    'Still_the_delivery_has_not_received_your_order_yet' => 'Still the delivery has not received your order yet',
    'The_Order_has_not_yet_been_processed' => 'The Order has not yet been processed',
    'Driver_coordinates_has_been_updated' => 'Driver coordinates has been updated',
    'not_found_this_copoun' => 'not found this copoun',
    'expired_copoun' => 'expired copoun',
    'Not_found_this_product' => 'Not found this product',
    'User_Profile_has_been_updated' => 'User Profile has been updated',
    'Account_deleted_successfully' => 'Account deleted successfully',
    'Location_added' => 'Location added successfully',
    'Not_found_this_location' => 'Not found this location',
    'Location_Updated' => 'Location updated successfully',
    'Location_Deleted' => 'Location deleted successfully',
    'FCM_Token_mobile_id_have_been_updated' => 'fcm_token & mobile_id have been updated',
    'Driver_not_exists' => 'Driver not exists',
    'Token_dosnt_generated' => 'Token dosn\'t generated',
    'Wait_the_admin_has_not_accepted_this_order_yet' => 'Wait, the admin has not accepted this order yet',
    'This_order_belongs_to_another_driver' => 'This order belongs to another driver',
    'This_Order_has_been_added_to_your_current_orders' => 'This Order has been added to your current orders',
    'This_order_already_added_to_rejected_list' => 'This order already added to rejected list',
    'The_order_was_excluded_from_the_orders_list' => 'The order was excluded from the orders list',
    'Order_Status_not_Prepared' => 'Order Status not Prepared',
    'You_have_already_changed_this_status' => 'You have already changed this status',
    'You_have_been_changed_the_order_status_to_on_the_way_to_customer' => 'You have been changed the order status to on the way to customer',
    'Order_Status_Error_not_Prepared_or_You_have_already_changed_this_status' => 'Order Status Error , not Prepared or You have already changed this status',
    'You_have_been_changed_the_order_status_to_Delivered' => 'You have been changed the order status to Delivered',
    'Driver_Profile_has_been_updated' => 'Driver Profile has been updated',
    'You_has_been_Marked_Your_Chats_as_Seen' => 'You has been Marked Your Chats as Seen',
    'Your_Notifications_Orders_that_Accepted_by_the_Admin' => 'Your Notifications & Orders that Accepted by the Admin',
    'Password_successfully' => 'Forgot Password successfully',
    'Not_Password_successfully' => 'Password has not been changed, try again',
    'Old_Password_Doesnt_match' =>'Old Password Doesn\'t match!',
    'Password_changed_successfully' => 'Password Changed Successfully',
    'complaint_successfully' => 'Complaint Successfully',
    'Not_complaint_successfully' => 'Not Complaint',
    'contact_successfully' => 'Contact Successfully',
    'Not_contact_successfully' => 'NOT Sant Contact',
    'updateBalance_successfully' => 'Update Balance Successfully',

    'add_review_successfully' => 'Add Review Successfully',

    'Been_Completed_Order' => 'Thank you for implementing the service',
    'Successfully' => 'Update Successfully',
    'the_code_is_invalid' => 'The Code Is Invalid',
    'successfully_added' => 'Added Successfully',

    // '' => '',








];
